### ISSUE TITLE
View is broken at the bottom.

### ISSUE THREAD

**Issue by ghost** [MarcinusX/bmi_calculator#10]
![screen shot 2018-11-05 at 2 23 44 pm](https://user-images.githubusercontent.com/3992738/47987882-af2fd100-e106-11e8-85d2-2037eed8972e.png)

**Comment by MarcinusX** [comment]
Wow, never seen that before.
Could you please reproduce it and send me the logs?
After that, could you download the latest version and check if it still occurs?

**Comment by ghost** [comment]
I checked, I have the latest code. This issue is occurring on Pixel 8.1 version simulator.

**Comment by MarcinusX** [comment]
And could you show me the error logs and output of `flutter doctor -v`?
