### ISSUE TITLE
Hello my friend, do you have any idea why this is happening?

### ISSUE THREAD

**Issue by Isonomic** [MarcinusX/bmi_calculator#7]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/Choreographer( 1502): Skipped 34 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 1502): eglMakeCurrent: 0xef97f2e0: ver 3 0 (tinfo 0xe8273cd0)
I/OpenGLRenderer( 1502): Davey! duration=729ms; Flags=1, IntendedVsync=55229025141473, Vsync=55229591808117, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=55229594840430, AnimationStart=55229595609460, PerformTraversalsStart=55229595819700, DrawStart=55229622915100, SyncQueued=55229641538330, SyncStart=55229649316520, IssueDrawCommandsStart=55229649994050, SwapBuffers=55229719895430, FrameCompleted=55229762241850, DequeueBufferDuration=26679000, QueueBufferDuration=2305000,
D/        ( 1502): HostConnection::get() New Host Connection established 0xe7cfde40, tid 1559
D/EGL_emulation( 1502): eglMakeCurrent: 0xef97f400: ver 3 0 (tinfo 0xe8273970)

**Comment by Isonomic** [comment]
Do you think it is the emulator I am running on?? I git cloned your app but it does not build fully. Please and thank you

**Comment by MarcinusX** [comment]
Hmmm... works fine on my computer...
Can you add more info like `flutter doctor` output?
